### PR TITLE
Added Selective decoding Options 

### PR DESCRIPTION
**Pull request by windkit**
### Description

JErasure would fix all missing data/code blocks, in storage system, only data blocks are need for normal operations (Degraded Read), code blocks fix are needed only for repair.
### Proposed Solution

To optimize, interfaces that allow selective decoding are added.
### Related PR

https://github.com/leo-project/jerasure/pull/3 (noalloc branch is used so...)
https://github.com/leo-project/leo_erasure/pull/1

### CODE REVIEW

**Comment by windkit** [comment]
@mocchira Rebased to remove duplicate commits, please check :)

**Comment by mocchira** [comment]
LGTM.
Thank you for your great contribution!

**Comment by yosukehara** [comment]
@windkit @mocchira 

I found a build issue on our Jenkins as bellow, please check that whether you can face same situation or not.

```
==> leo_erasure (compile)
c_src/jerasure/src/.libs/jerasure.o: 関数 `jerasure_matrix_decode_selected' 内:
jerasure.c:(.text+0xb38): `jerasure_matrix_decode_selected' が重複して定義されています
c_src/jerasure_mod.o:/var/lib/jenkins/jobs/Tests_for_aws-sdk_clients_with_LeoFS/workspace/leofs/deps/leo_erasure/c_src/jerasure_mod.cpp:168: ここで最初に定義されています
c_src/jerasure/src/.libs/jerasure.o: 関数 `jerasure_matrix_decode_data' 内:
jerasure.c:(.text+0x1420): `jerasure_matrix_decode_data' が重複して定義されています
c_src/jerasure_mod.o:/var/lib/jenkins/jobs/Tests_for_aws-sdk_clients_with_LeoFS/workspace/leofs/deps/leo_erasure/c_src/jerasure_mod.cpp:67: ここで最初に定義されています
c_src/jerasure/src/.libs/jerasure.o: 関数 `jerasure_schedule_decode_data_lazy' 内:
jerasure.c:(.text+0x4ce6): `jerasure_schedule_decode_data_lazy' が重複して定義されています
c_src/jerasure_mod.o:/var/lib/jenkins/jobs/Tests_for_aws-sdk_clients_with_LeoFS/workspace/leofs/deps/leo_erasure/c_src/jerasure_mod.cpp:297: ここで最初に定義されています
c_src/jerasure/src/.libs/jerasure.o: 関数 `jerasure_schedule_decode_selected_lazy' 内:
jerasure.c:(.text+0x5137): `jerasure_schedule_decode_selected_lazy' が重複して定義されています
c_src/jerasure_mod.o:/var/lib/jenkins/jobs/Tests_for_aws-sdk_clients_with_LeoFS/workspace/leofs/deps/leo_erasure/c_src/jerasure_mod.cpp:326: ここで最初に定義されています
collect2: error: ld returned 1 exit status
ERROR: sh(cc c_src/cauchycoding.o c_src/coding.o c_src/common.o c_src/irscoding.o c_src/jerasure_mod.o c_src/leo_erasure_nif.o c_src/liberationcoding.o c_src/rscoding.o  -lstdc++ -shared  -L"/usr/local/erlang/17.5/lib/erlang/lib/erl_interface-3.7.20/lib" -lerl_interface -lei c_src/gf-complete/src/.libs/*.o c_src/jerasure/src/.libs/*.o c_src/isa-l/erasure_code/.libs/*.o -o priv/leo_erasure.so)
failed with return code 1 and the following output:
c_src/jerasure/src/.libs/jerasure.o: 関数 `jerasure_matrix_decode_selected' 内:
jerasure.c:(.text+0xb38): `jerasure_matrix_decode_selected' が重複して定義されています
c_src/jerasure_mod.o:/var/lib/jenkins/jobs/Tests_for_aws-sdk_clients_with_LeoFS/workspace/leofs/deps/leo_erasure/c_src/jerasure_mod.cpp:168: ここで最初に定義されています
c_src/jerasure/src/.libs/jerasure.o: 関数 `jerasure_matrix_decode_data' 内:
jerasure.c:(.text+0x1420): `jerasure_matrix_decode_data' が重複して定義されています
c_src/jerasure_mod.o:/var/lib/jenkins/jobs/Tests_for_aws-sdk_clients_with_LeoFS/workspace/leofs/deps/leo_erasure/c_src/jerasure_mod.cpp:67: ここで最初に定義されています
c_src/jerasure/src/.libs/jerasure.o: 関数 `jerasure_schedule_decode_data_lazy' 内:
jerasure.c:(.text+0x4ce6): `jerasure_schedule_decode_data_lazy' が重複して定義されています
c_src/jerasure_mod.o:/var/lib/jenkins/jobs/Tests_for_aws-sdk_clients_with_LeoFS/workspace/leofs/deps/leo_erasure/c_src/jerasure_mod.cpp:297: ここで最初に定義されています
c_src/jerasure/src/.libs/jerasure.o: 関数 `jerasure_schedule_decode_selected_lazy' 内:
jerasure.c:(.text+0x5137): `jerasure_schedule_decode_selected_lazy' が重複して定義されています
c_src/jerasure_mod.o:/var/lib/jenkins/jobs/Tests_for_aws-sdk_clients_with_LeoFS/workspace/leofs/deps/leo_erasure/c_src/jerasure_mod.cpp:326: ここで最初に定義されています
collect2: error: ld returned 1 exit status
```

**Comment by windkit** [comment]
@yosukehara the corresponding PR in `leo_erasure` is still in testing, that is the cause of the problem.

**Comment by windkit** [comment]
This reveals the problem of current `c_src/build_deps.sh` in `leo_erasure`.
It always uses the `develop` branch of `jerasure`

**Comment by mocchira** [comment]
@windkit yes. should be tagged at some point ( such as when 1.4 will be released )

**Comment by yosukehara** [comment]
@windkit @mocchira I've just confirmed our Jenkins has passed a integration-test. Thanks a lot.

**Pull request merged**
